import discord
from discord.ext import commands

class ChessCommands(commands.Cog):
    # Ignore channel restrictions if you want help menus accessible everywhere
    ignore_global_check = True 

    def __init__(self, bot):
        self.bot = bot

    @commands.command(name="chess_cmds", help="Display the tactical manual for the MSdos Chess Engine.")
    async def chess_cmds(self, ctx):
        embed = discord.Embed(
            title="♟️ MSdos Chess Engine | Command Manual",
            description="Welcome to the tactical grid. Use these commands to interface with the local chess matrix.",
            color=0x2B2D31  # Sleek dark theme color
        )
        
        embed.add_field(
            name="🏁 `*play_chess <ai/player> [easy/medium]`",
            value="Initialize a new board. \n**Examples:**\n`*play_chess ai medium` (Play the bot)\n`*play_chess player` (Open a multiplayer lobby)",
            inline=False
        )
        
        embed.add_field(
            name="🤝 `*accept_chess <code>`",
            value="Link into an open multiplayer lobby. You will need the 5-character match code generated by the host.",
            inline=False
        )
        
        embed.add_field(
            name="⚔️ `*move_chess <code> <coordinates>`",
            value="Execute a positional maneuver using standard UCI format.\n**Example:** `*move_chess AX83 e2e4` moves the piece at E2 to E4.",
            inline=False
        )
        
        embed.set_footer(text="MSdos.vxd Entertainment Subsystem • Module: Chess")
        
        await ctx.send(embed=embed)

async def setup(bot):
    await bot.add_cog(ChessCommands(bot))
